import { Category, Transaction } from "./types";

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: "cat-salario",
    name: "Salário & Renda",
    type: "income",
    color: "#10b981",
    icon: "Briefcase",
  },
  {
    id: "cat-invest",
    name: "Investimentos & Dividendos",
    type: "income",
    color: "#06b6d4",
    icon: "TrendingUp",
  },
  {
    id: "cat-freelance",
    name: "Freelance & Projetos",
    type: "income",
    color: "#8b5cf6",
    icon: "Laptop",
  },
  {
    id: "cat-extra",
    name: "Outros Rendimentos",
    type: "income",
    color: "#34d399",
    icon: "PlusCircle",
  },

  {
    id: "cat-alimentacao",
    name: "Alimentação & Mercado",
    type: "expense",
    color: "#f59e0b",
    icon: "Utensils",
  },
  {
    id: "cat-moradia",
    name: "Moradia, Aluguel & Contas",
    type: "expense",
    color: "#ef4444",
    icon: "Home",
  },
  {
    id: "cat-transporte",
    name: "Transporte & Combustível",
    type: "expense",
    color: "#3b82f6",
    icon: "Car",
  },
  {
    id: "cat-lazer",
    name: "Lazer & Entretenimento",
    type: "expense",
    color: "#ec4899",
    icon: "Film",
  },
  {
    id: "cat-saude",
    name: "Saúde & Farmácia",
    type: "expense",
    color: "#14b8a6",
    icon: "HeartPulse",
  },
  {
    id: "cat-educacao",
    name: "Educação & Cursos",
    type: "expense",
    color: "#6366f1",
    icon: "GraduationCap",
  },
  {
    id: "cat-compras",
    name: "Compras Pessoais",
    type: "expense",
    color: "#a855f7",
    icon: "ShoppingBag",
  },
  {
    id: "cat-outros",
    name: "Outras Despesas",
    type: "expense",
    color: "#64748b",
    icon: "CreditCard",
  },
];

export const INITIAL_SAMPLE_TRANSACTIONS: Transaction[] = [
  {
    id: "tx-1",
    category_id: "cat-salario",
    amount: 8500.0,
    type: "income",
    date: "2026-09-05",
    description: "Salário Mensal",
    notes: "Depósito em conta corrente",
  },
  {
    id: "tx-2",
    category_id: "cat-freelance",
    amount: 2200.0,
    type: "income",
    date: "2026-09-12",
    description: "Consultoria Web App",
    notes: "Projeto Next.js entregue",
  },
  {
    id: "tx-3",
    category_id: "cat-moradia",
    amount: 2400.0,
    type: "expense",
    date: "2026-09-06",
    description: "Aluguel & Condomínio",
  },
  {
    id: "tx-4",
    category_id: "cat-alimentacao",
    amount: 1150.8,
    type: "expense",
    date: "2026-09-08",
    description: "Compras Supermercado",
  },
  {
    id: "tx-5",
    category_id: "cat-transporte",
    amount: 320.0,
    type: "expense",
    date: "2026-09-10",
    description: "Combustível & Estacionamento",
  },
  {
    id: "tx-6",
    category_id: "cat-invest",
    amount: 450.0,
    type: "income",
    date: "2026-09-14",
    description: "Dividendos FIIs & Ações",
  },
  {
    id: "tx-7",
    category_id: "cat-lazer",
    amount: 280.5,
    type: "expense",
    date: "2026-09-15",
    description: "Jantar com amigos & Cinema",
  },
  {
    id: "tx-8",
    category_id: "cat-saude",
    amount: 190.0,
    type: "expense",
    date: "2026-09-16",
    description: "Medicamentos & Suplementos",
  },
];
